name: Katheryne's Commons CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: installing deps
        run: npm install
      - uses: actions/cache@v2
      - name: cache deps
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: $${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: building lib
        run: npm run build
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: testing lib
        run: npm run test
  coverage:
    needs: [ install, test ]
    runs-on: ubuntu-latest
    steps:
      - name: publish coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 377d361f65561e14524d09d6b0ab938a2bebc37c144cb9230d1f9470119d45f5

