name: Katheryn (commons) library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: building katheryne (commons)
        run: npm i && npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: testing katheryne (commons)
        run: npm i && npm run test
